### ISSUE TITLE
Light Dark <code> Size

### ISSUE THREAD

**Issue by goldbattle** [mosra/m.css#105]
The light theme has a different font size for code blocks which makes its text be cut off and the overall font size is a lot smaller. I think the dark theme has good values imo.

https://github.com/mosra/m.css/blob/master/css/m-theme-light.css#L29-L30
![image](https://user-images.githubusercontent.com/2222562/58731430-ac573f00-83bc-11e9-8038-3566eff8a769.png)

vs
https://github.com/mosra/m.css/blob/master/css/m-theme-dark.css#L29-L30
![image](https://user-images.githubusercontent.com/2222562/58731405-9ba6c900-83bc-11e9-9a5e-3fbed8b67a97.png)

**Comment by mosra** [comment]
Hi, the light theme is unfortunately quite neglected and (due to how busy I am) I'm afraid it won't improve any time soon. If you want to update it to look better, I'll gladly accept a pull request :)

**Comment by goldbattle** [comment]
I ended up creating a custom theme which addressed all my specific issues:
https://github.com/rpng/open_vins/tree/master/docs/mcss_theme
