### ISSUE TITLE
Typo in m-components.css

### ISSUE THREAD

**Issue by grisumbras** [mosra/m.css#118]
https://github.com/mosra/m.css/blob/f19ee26f7543ee9ce0ebd8fb53e4287f4068cd92/css/m-components.css#L1033

`.m-block.m-flat h5.` should probably be `.m-block.m-flat h5,`

**Comment by mosra** [comment]
You're right, thank you! Fixed in f239c938e90d2d1409ea3a97dc91ce3d41a3f7be.
