### ISSUE TITLE
Support reStructuredText code directive aliases

### ISSUE THREAD

**Issue by gsauthof** [mosra/m.css#153]
The [m.code](https://mcss.mosra.cz/plugins/math-and-code/#code) plugin overwrites the docutils `code` directive such that the CSS class `m-code` is emitted instead of the default `highlight` class, in the generated html.

It turns out that docutils currently define 3 code block directives that alias each other, namely `code`, `code-block` and `sourcecode`:

https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/parsers/rst/languages/en.py#L22-L24

Current [documentation even only mentions](https://www.sphinx-doc.org/en/1.8/usage/restructuredtext/directives.html#directive-code-block) `code-block` and `sourcecode`.

Since I've some existing `.rst` files that use `code-block` I quickly patched `code.py` which seems to work so far:

```
--- a/plugins/m/code.py
+++ b/plugins/m/code.py
@@ -282,6 +282,7 @@ code.options = {'class': directives.class_option,
 
 def register_mcss(mcss_settings, **kwargs):
     rst.directives.register_directive('code', Code)
+    rst.directives.register_directive('code-block', Code)
     rst.directives.register_directive('include', Include)
     rst.roles.register_canonical_role('code', code)
 
```

Perhaps there is a better way to fix this instead of registering `code-block` and `sourcecode` in this way.

**Comment by mosra** [comment]
Hi, 

I was aware there's a bunch of aliases (and Sphinx for some reason prefers the most verbose one) but to me those seemed unnecessarily redundant, so I added just `.. code::` one. But now, after thinking about this a bit more, it doesn't make sense to have `.. code::` work while `.. code-block::` still uses the unpatched/broken vanilla directive. So I added both aliases in bfc0b365769ea2002c88c18fd1ef5996d933eb32.
