### ISSUE TITLE
don't display summary and content

### ISSUE THREAD

**Issue by paulignari** [mosra/m.css#16]
In index pages (archive, index) the 1st commit show all its content, but
is preceded by the summary, so first lines are repeated twice.

The same happens in article.

I removed the summary part from article_header, and placed where needed in
conditional statements.

I  made pull request #14 with my patch

**Comment by mosra** [comment]
Hi,

the theme assumes that you set the `:summary:` field in articles explicitly, because otherwise Pelican autogenerates the summary from first few paragraphs of the content and then it appears duplicated on the page. So in order to fix the problem, you would write your content like this:

```rst
An Article
##########

:date: 2017-12-04
:summary: Article summary paragraph. More lines of the summary,
    wrapped like this. Summary summary lalala.

First paragraph of article content. 

Second paragraph of article content. More content.
```

Instead of:

```rst
An Article
##########

:date: 2017-12-04

Article summary paragraph. More lines of the summary,
wrapped like this. Summary summary lalala.

First paragraph of article content.  

Second paragraph of article content. More content.
```

Would this solution work for you? I'm using it this way on for example http://blog.magnum.graphics/ and unfortunately the patch in #14 would break it -- the articles would then miss their first paragraph in the detail view...

I'll update the documentation to state this more clearly.

**Comment by theindigamer** [comment]
I had a similar requirement for my blog and what I did was create a new `article_no_summary.html` file, which I use for short stories by specifying `:template: article_no_summary` in the `.rst` file. So the automatic summary gives a (hopefully enticing) glimpse of what is inside; this is sometimes nicer than giving a summary of the story up front.

https://github.com/theindigamer/m.css/tree/del-summary/pelican-theme/templates

**Comment by mosra** [comment]
I think I see the point now, thanks!

With 7910a9090ae6a04113d4b9068585dc36cc917efb there's an ability to configure the summary appearance either on a global or a per-article basis. [See the docs for details.](http://mcss.mosra.cz/pelican/theme/#controlling-article-appearance)

Also, @theindigamer, great to see m.css used on your site! :) I made a bunch of improvements that might be useful for you:

- With d3560de0e6d0ae17053e99881bb820be3074bfdd it's possible to configure paragraph indentation directly from the theme file so you don't need to patch `m-components.css` directly.
- With 7910a9090ae6a04113d4b9068585dc36cc917efb (again), it's possible to disable expansion of the first article (again either globally or per article). [Docs.](http://mcss.mosra.cz/pelican/theme/#controlling-article-appearance)
- And 32e9befd3b34d05e95acb9be67574d4e9e79fb7e gives more flexibility for the footer navigation. In particular, it's completely hidden by default. [Docs.](http://mcss.mosra.cz/pelican/theme/#footer-navigation)

Closing as resolved then. Please reopen (or open new issue(s)) if you encounter any problems.

**Comment by paulignari** [comment]
Great job, Vladimír.


I have checked fastly your patches and I think they fulfill my need of 
hiding summaries.


Easy configuration of paragraph indentation and justification is 
awelcome addition.



-- 

Mandi.

Paolo

**Comment by mosra** [comment]
Great, thank you :)
