### ISSUE TITLE
./doxygen.py path/to/your/Doxyfile-mcss File not found error

### ISSUE THREAD

**Issue by kennychowdhary** [mosra/m.css#172]
When running ./doxygen.py path/to/your/Doxyfile-mcss, where I replaced the path with the absolute path, I get the following error:

Traceback (most recent call last):
  File "./doxygen.py", line 3847, in <module>
    os.makedirs(state.doxyfile['OUTPUT_DIRECTORY'], exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

I verified that the requisite Doxyfile and Doxyfile-mcss is in the proper directory. I am using Python 3.7 and doxygen 1.8.18.

**Comment by mosra** [comment]
Hi, sorry for answering three months late, too much stuff on my plate :sweat_smile: 

Well, that's silly. I expected `makedirs()` to just be a no-op when it gets an empty argument. Fixed in daef291c943073b8cb7391c154ad48c948da1574.
