### ISSUE TITLE
file inclusion question

### ISSUE THREAD

**Issue by fnrizzi** [mosra/m.css#188]
Hi! 
I am using the m.css and I have the following issue: i have a mardown document that I compile with the `./doxygen` and I would like to include in my markdown file some code from a .cpp file. 
I could copy and past the code, but that is redundant and I have to redo it everytime the cpp file changes. 

I was wondering if the file inclusion explained here: https://mcss.mosra.cz/plugins/math-and-code/#advanced-file-inclusion
is also available for doxygen/markdown? If not, is there a way i can mix rst code and markdown to obtain that capability?

Or do you have any other suggestion to solver my problem? 
Thanks!

**Comment by mosra** [comment]
(Sorry for *embarrassingly* late replies, finally got a chance to get back to this project.)

This is achievable using vanilla Doxygen functionality -- please see the `@snippet`, `@include`, `@skip`, `@until` and `@skipline` [builtin commands](https://www.doxygen.nl/manual/commands.html). Especially the `@snippet` command is very powerful, allowing you to include exact delimited pieces of code, while still keeping the code itself compilable.

For an ~~overwhelming~~ exhaustive usage example, here's what I do in Magnum: 

- [C++ snippet code delimited with comments](https://github.com/mosra/magnum/blob/a146f9f74b5224367ea6efd2f755958686a984a5/doc/snippets/MagnumSceneTools.cpp#L59-L71) -- note that this code is compiled as part of my test suite to ensure the syntax is alright and up-to-date, the `DOXYGEN_ELLIPSIS()` is for the compiler just a pass-through `#define DOXYGEN_ELLIPSIS(...) __VA_ARGS__` but in the output it gets replaced with just `…` to hide unnecessary complexity
- [A docblock referencing this snippet](https://github.com/mosra/magnum/blob/a146f9f74b5224367ea6efd2f755958686a984a5/src/Magnum/SceneTools/FlattenMeshHierarchy.h#L70-L92)
- [A `Doxyfile` `EXAMPLE_PATH` option to point to where the snippets are](https://github.com/mosra/magnum/blob/a146f9f74b5224367ea6efd2f755958686a984a5/doc/Doxyfile#L1023-L1024)
- [A snippet pre-processing hook that turns the `DOXYGEN_ELLIPSIS()` macro into a literal ellipsis](https://github.com/mosra/magnum/blob/a146f9f74b5224367ea6efd2f755958686a984a5/doc/conf.py#L44-L67)
- [The resulting generated documentation](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1SceneTools.html#ab03c8e246362b14d7e1b52920633b219)
