### ISSUE TITLE
how to correctly document the full templated functions

### ISSUE THREAD

**Issue by tsung-wei-huang** [mosra/m.css#199]
It looks like I am not able to document the full function with template arguments but only a brief statement. For example, in my project, [this in-code doc](https://github.com/taskflow/taskflow/blob/82c0d7048819efd949b12d53176765218f3495ef/taskflow/cuda/cuda_algorithm/cuda_sort.hpp#L448) can only be correctly processed by `doxygen.py` with `@brief`.  Ideally, I would like to have the following:

```
/**
@fn cuda_sort
@tparam P execution policy type
@tparam K_it keys iterator type
@tparam V_it values iterator type
@tparam C comparator type
@brief performs key-value sort on a range of items
*/
```

However, when I use `doxygen.py` to run my [conf.py](https://github.com/taskflow/taskflow/blob/master/doxygen/conf.py), the function is not documented. Would you please help take a look? I believe I mark this file to be [documented](https://github.com/taskflow/taskflow/blob/82c0d7048819efd949b12d53176765218f3495ef/taskflow/cuda/cuda_algorithm/cuda_sort.hpp#L8).

**Comment by mosra** [comment]
Hi!

Interesting. This is something I do quite often and it works, although I have the doc commands in different order. Can you try this instead? If the doc block is right above the function, you shouldn't even need the `@fn`:

```cpp
/**
@brief performs key-value sort on a range of items
@tparam P execution policy type
@tparam K_it keys iterator type
@tparam V_it values iterator type
@tparam C comparator type

It should be able to consume detailed description as well, if it's put here.
*/
```

**Comment by tsung-wei-huang** [comment]
@mosra thanks. This indeed fixes it - order matters.
