### ISSUE TITLE
m.images breaks if photo has exif but no FNumber element

### ISSUE THREAD

**Issue by jelmer** [mosra/m.css#20]
m.images currently breaks when there is no FNumber property in exif data, but other exif data properties are set.

Just catching KeyError and setting caption to an empty string works around this issue.

**Comment by mosra** [comment]
Hi, I'm currently writing thorough tests for all the functionality and this is definitely on my list. Give me a day or two :)

**Comment by mosra** [comment]
Should be fixed in 92e90ca7c97fe75b09046457dda1b9980fd8aed7. Thanks for reporting this :)
