### ISSUE TITLE
ARGH!  FontAwesome is not so Awesome.

### ISSUE THREAD

**Issue by egberts** [mosra/m.css#223]
Not sure what is happening....

https://egbert.net/blog/drafts/articles/ssh-openssh-certificates.html

Those spaces in the monospace font are not "evenly the same" width as the other characters.

Is it my space's character width of `FontAwesome` font?  Or the kerning via CSS in Firefox?  I couldn't tell.

But what I did do, is press F12 (Firefox), jumped to <body><main><div><div><article<codehilite> and replaced/poke `Courier` instead of `FontAwesome`, and it finally worked in correctly the alignment of columns in code sections.

Must be my font, not the `m.css` character kerning, right?

**Comment by crisluengo** [comment]
Looks to me that you didn’t pick a monospaced font. The space is much narrower than any letter. This has nothing to do with FontAwesome, or with kerning. The font is just not suitable.

**Comment by egberts** [comment]
indeed
