### ISSUE TITLE
warning: unknown <sectiondef> kind property and failure with AssertionError

### ISSUE THREAD

**Issue by rajendrasp** [mosra/m.css#231]
I am getting lot of following warnings and then no output doc is generated in html file. 

WARNING:root:class_<long_class_name>.xml: unknown <sectiondef> kind property

And then I get following assert

Traceback (most recent call last):
  File "E:\Code\m.css\src\m.css\documentation\doxygen.py", line 4014, in <module>
    run(state, templates=os.path.abspath(args.templates), wildcard=args.wildcard, index_pages=args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "E:\Code\m.css\src\m.css\documentation\doxygen.py", line 3868, in run
    parsed = parse_xml(state, file)
  File "E:\Code\m.css\src\m.css\documentation\doxygen.py", line 2896, in parse_xml
    assert compound.kind in ['class', 'struct', 'union']
AssertionError

**Comment by mosra** [comment]
Hello! That seems like it's building documentation for a language other than C or C++ (which has properties as a language features, such as Python or C#), is it possible?

The Doxygen wrapper isn't really suited for anything else than C/C++ at the moment, unfortunately. For Python there's a separate tool, however, if that's your case: https://mcss.mosra.cz/documentation/python/

**Comment by rajendrasp** [comment]
Ohh I see. Yes I am trying with C# project. Thanks for clarifying. Is  there a plan to support other languages?

**Comment by mosra** [comment]
I did some prototyping for Doxygen-less C# support (similarly to Python, by using C#'s builtin reflection capabilities), but had to put it aside due to lack of time -- I'm constantly working on too many things.

I might revive that eventually if there's enough demand, but can't promise anything.

**Comment by mosra** [comment]
As of 62768962f9cf167291bae2df518de0c89d6836cf, the script ignores all files that aren't C or C++ with a warning, so it shouldn't blow up unexpectedly anymore.
