### ISSUE TITLE
Adding search, for an m.css newbie

### ISSUE THREAD

**Issue by maphew** [mosra/m.css#234]
I see a number of issues and PR in m.css github related to search functionality but I haven't found anything in the docs yt about how to turn it on or configure it. (It's not a [listed plugin](https://mcss.mosra.cz/plugins/) for example.) Where do I get started? Are the discussions here referring to the official plugin or something else?

I've gotten some results following https://github.com/pelican-plugins/search but I'm not happy with the search box placement I have. I'm not sure where in `m.css/.../templates/base.html` it should go or even if that's the right file to be using.

**Comment by mosra** [comment]
Hi, the [search functionality](https://blog.magnum.graphics/meta/implementing-a-fast-doxygen-search/) is currently limited to Python and Doxygen documentation generators, not the Pelican theme. 

In particular, it was designed mainly for searching symbols / API names by a prefix, not for a fulltext search in general prose content. I can imagine it could work for searching page / article / section titles, but even that would be probably useless in practice.

**Comment by maphew** [comment]
Ah, ok. Thanks for the background. I'll close this for now, since I've run into other problems to deal with, and come back and open this when I'm ready to participate in figuring it out.
