### ISSUE TITLE
m.css theme applied on main page but not on others

### ISSUE THREAD

**Issue by JosueGauthier** [mosra/m.css#237]
Hello, 
I want to use the m.css theme with Doygen to generate a HTML site for my doc, so i generate via ```./doxygen.py ../../Doxyfile-mcss```
And so on index.html i obtain this :

![Screenshot from 2023-05-02 18-04-50](https://user-images.githubusercontent.com/20337589/235722182-fd552c30-5051-440d-9599-7118dc06216a.png)
But on other page i obtain the old dogen theme :
![Screenshot from 2023-05-02 18-06-48](https://user-images.githubusercontent.com/20337589/235722509-56e3c2d9-e9a6-4422-9da2-1e144d73f669.png)

I change nothing to the Doxyfile 
and here is my Doxyfile-mcss 

```
@INCLUDE                = Doxyfile
GENERATE_HTML           = YES
GENERATE_LATEX          = NO
GENERATE_XML            = NO
M_SHOW_UNDOCUMENTED     = YES
```
Do you have any ideas ? Thanks,

**Comment by mosra** [comment]
Ha, sorry for taking three centuries to answer :see_no_evil: 

You have the `Doxyfile-mcss` backwards, it needs to be this instead:

```ini
@INCLUDE                = Doxyfile
GENERATE_HTML           = NO
GENERATE_LATEX          = NO
GENERATE_XML            = YES
M_SHOW_UNDOCUMENTED     = YES
```
