### ISSUE TITLE
Cover image doesn't render on my Windows 10 

### ISSUE THREAD

**Issue by jegrami** [mosra/m.css#242]
The `:cover:` tag doesn't seem to work for me even though I followed the exact file structure the author used for the m.css project website. My index page is in `content/`. The cover image is in `content/static/cover.jpg`. On the index page, I reference the image like this: `:cover: {static}/static/cover.jpg`. 

But it doesn't render. What I'm I missing? Please help!

**Comment by mosra** [comment]
I have to admit I don't remember how exactly this works in Pelican but in the `pelicanconf.py` I have these two additional options:

```py
STATIC_URL = '{path}'
STATIC_PATHS = ['static']
```

So maybe those two are what makes it work? If it doesn't, what image address is generated in the output HTML?

**Comment by jegrami** [comment]
Yes, you're right. It works now. Thanks!
