### ISSUE TITLE
How to colorized a word or sentence.

### ISSUE THREAD

**Issue by egberts** [mosra/m.css#246]
Maybe I am stupid, but I've tried to colorized the text using `<span style color:red>Red text</span>` but no dice:

Using this example Markdown file:
```markdown
Throughout the following sections note:

* <span style="color:red;">Red text</span> indicates deprecated macros ...

* <span style="color:green;">Green text</span> indicates recommended macros ...
```
and it produces ... no change.

Firefox Inspector reported:
```html
<span style="">Red text</span> indicates deprecated macros ...
<span style="">Green text</span> indicates recommended macros ...
```
Reference: https://egbert.net/blog/articles/detect-os-using-compiler-predefined-macros.html

So, is there some CSS I must use to support my goal of colorizing a text string in HTML?  Or something simpler? 

(BTW, who stripped my `style=""` options off?

**Comment by egberts** [comment]
Could it be that I too must have a supporting CSS and do the following?

Html:

```html
<p>For example different coloured in-line <code class="red">code in red</code> and <code class="green">green</code>.</p>
```
Along with the following css in main.css.

```css
code.red {color:red;}
code.green {color: green;}
```

That's just for anything surrounding by a pair of backticks ('`').

**Comment by mosra** [comment]
For colored text, there's the pre-defined CSS styles shown at https://mcss.mosra.cz/css/components/#text It's not *red* red, but pretty close, and as a bonus you have a chance to tune the colors for your theme without having to update all cases where they're used.

So in case of Markdown it'd be `<span class="m-text m-danger">text in red</span>`, I think? No idea what the Markdown processor is capable of, again, so maybe you'd have to try a bunch of variants before it sticks. 

For reST you'd do

```rst
.. defined at the top
.. role:: text-danger
    :class: m-text m-danger
    
...
    
This is a :text-danger:`red text`.
```
