### ISSUE TITLE
error message HTML sanity 

### ISSUE THREAD

**Issue by arnauldb** [mosra/m.css#32]
Hello,

I try to use Html sanity. I put the htmlsanity.py file in a "m" directory (pelican/plugins/m).

Added to my pelicanconf.py:
```
PLUGINS = ['m.htmlsanity']
M_HTMLSANITY_SMART_QUOTES = True
M_HTMLSANITY_HYPHENATION = True
```

Installed the Pyphen li­brary using: `pip install Pyphen`

But I have this error:
```
ERROR: Cannot load plugin `m.htmlsanity`
     | ImportError: No module named m.htmlsanity
```

Thank you for any help.

**Comment by mosra** [comment]
Hi,

what's your `PLUGIN_PATHS` setting? It should point to the base directory where you put the plugins so it knows where to look, relative to your `pelicanconf.py`. In your case that would be probably this:

```py
PLUGIN_PATHS = ['pelican/plugins']
```

**Comment by mosra** [comment]
Closing as resolved.
