### ISSUE TITLE
dox2html5.py fails when encountering @exception

### ISSUE THREAD

**Issue by anderslanglands** [mosra/m.css#34]
exception commands in the documentation cause dox2html5.py to fail an assertion deep in `parse_desc_internal()`. The following fix will at least get the documentation to build when inserted in the if statement at line 920:
```
                    elif i.attrib['kind'] == 'exception':
                        # FIXME: what do we do with exceptions?
                        pass

```
A better solution would be to add handling for this properly and make it part of the documentation but I am not familiar enough with the code yet to add that.

**Comment by mosra** [comment]
Implemented in 188b8a40fb577710166b1d416b540ec7cfc3eff6. I was not aware this command is a thing :) Please reopen if you find a problem with this.
