### ISSUE TITLE
Remove paragraph indent after code block

### ISSUE THREAD

**Issue by bjfar** [mosra/m.css#38]
To get a nicely formatted code block, it seems the Doxygen thing to do is:

```
Some text

\code
My code here
\endcode

Some more text
```

Which works fine, however m.css seems to indent the following text paragraph without exception. I tried removing the newline between the code block and test, but this just puts the text inline with the code block.

Grammatically there are often cases where a code block forms part of a paragraph, even a sentence, so starting a new paragraph after one doesn't always make sense.  I guess in standard Doxygen this doesn't come up as a problem since they don't use indenting for paragraphs, but with indented paragraphs the distinction becomes visible.

Do you know any way around this?

**Comment by mosra** [comment]
@bjfar did this suggestion solve your problem?

**Comment by jbakosi** [comment]
I tried option 1, and it works fine.

**Comment by bjfar** [comment]
Ah sorry, these solutions were a bit complicated so I haven't bothered to try any of them yet.

**Comment by mosra** [comment]
Closing as resolved.
