### ISSUE TITLE
AssertionError parsing xml

### ISSUE THREAD

**Issue by bjfar** [mosra/m.css#39]
This might be caused by a similar thing as #37, but it is not obviously the case to me so I'll report it. A colleague of mine added a documentation page to our project (attached) and managed to kill the dox2html5.py script with it:

```
DEBUG:root:Parsing _plugin__declaration__section.xml
WARNING:root:_plugin__declaration__section.xml: inline code has multiple lines, fallback to a code block
WARNING:root:_plugin__declaration__section.xml: no filename attribute in <programlisting>, assuming C++
WARNING:root:_plugin__declaration__section.xml: ignoring <hruler> in desc
Traceback (most recent call last):
  File "/home/farmer/repos/gambit/myfork/m.css/doxygen/dox2html5.py", line 2895, in <module>
    run(doxyfile, os.path.abspath(args.templates), args.wildcard, args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "/home/farmer/repos/gambit/myfork/m.css/doxygen/dox2html5.py", line 2813, in run
    parsed = parse_xml(state, file)
  File "/home/farmer/repos/gambit/myfork/m.css/doxygen/dox2html5.py", line 1938, in parse_xml
    compound.description, templates, compound.sections, footer_navigation, example_navigation, search_keywords, compound.is_deprecated = parse_toplevel_desc(state, compounddef.find('detaileddescription'))
  File "/home/farmer/repos/gambit/myfork/m.css/doxygen/dox2html5.py", line 1316, in parse_toplevel_desc
    parsed = parse_desc_internal(state, element)
  File "/home/farmer/repos/gambit/myfork/m.css/doxygen/dox2html5.py", line 719, in parse_desc_internal
    add_css_class=add_css_class)
  File "/home/farmer/repos/gambit/myfork/m.css/doxygen/dox2html5.py", line 789, in parse_desc_internal
    assert row.tag == 'row'
AssertionError
```

I think his new page is far from bug free, however I guess it anyway should not kill the script like this.

[_plugin__declaration__section_xml.txt](https://github.com/mosra/m.css/files/1954917/_plugin__declaration__section_xml.txt)
[README_plugin_dox.txt](https://github.com/mosra/m.css/files/1954918/README_plugin_dox.txt)

Edit: oh wait, I think that is the wrong page, I think this is the one that generates the problematic XML:
[scanner_dox.txt](https://github.com/mosra/m.css/files/1955089/scanner_dox.txt)

**Comment by mosra** [comment]
Table captions are implemented in cb0c6101be6008a7eae7292c54f9fcbc5f15b243, so it should not assert anymore. Please reopen if there's still something asserting, I made just a minimal repro case with `<caption>` inside `<table>`.
