### ISSUE TITLE
DATE_FORMATS on Xubuntu/Ubuntu pelicanconf.py

### ISSUE THREAD

**Issue by gotchafr** [mosra/m.css#4]
Hi mosra,

On Ubuntu the date format 

`DATE_FORMATS = {'en': ('en_US', '%b %d %Y')}`

produces the error below...

I had to change to 

`DATE_FORMATS = {'en': ('en_US.UTF-8', '%b %d %Y')}`

in order to process the site without errors. I don't know how to handle this in an elegant fashion. Testing `sys.platform == 'linux'`in the pelicanconf is not very nice. Perhaps just add a comment as I did on my fork:

```
#On Linux systems use the second format
DATE_FORMATS = {'en': ('en_US', '%b %d %Y')}
#DATE_FORMATS = {'en': ('en_US.UTF-8', '%b %d %Y')}

```
This is the error...
```
ERROR: Could not process pelican/theme.rst
  | Error: unsupported locale setting
  |___
  | Traceback (most recent call last):
  |   File "/home/gotcha/.virtualenvs/pelican/lib/python3.5/site-packages/pelican/generators.py", line 629, in generate_context
  |     context_sender=self)
  |   File "/home/gotcha/.virtualenvs/pelican/lib/python3.5/site-packages/pelican/readers.py", line 572, in read_file
  |     context=context)
  |   File "/home/gotcha/.virtualenvs/pelican/lib/python3.5/site-packages/pelican/contents.py", line 123, in __init__
  |     locale.setlocale(locale.LC_ALL, locale_string)
  |   File "/home/gotcha/.virtualenvs/pelican/lib/python3.5/locale.py", line 594, in setlocale
  |     return _setlocale(category, locale)
  | locale.Error: unsupported locale setting
```
Cheers...

**Comment by mosra** [comment]
Hi, sorry, didn't see that you opened also these issues :) 

This one is fixed with #5 and ba031f351c568cbc5e9fd6d0f8de7c1d1a88b353, then. I think I'll need to use `sys.platform` at some point anyway, see https://github.com/mosra/magnum-website/pull/1
