### ISSUE TITLE
m.abbr depends upon the init file

### ISSUE THREAD

**Issue by joshfuggle** [mosra/m.css#48]
Hey mate,

As the title says. The m.abbr file depends upon parse_link function found in the init file. Which is fine, probably, but the doco doesn't mention it. Need to dive in to the code when installing the plugin to find out what is causing the exception.

JF

**Comment by mosra** [comment]
Ugh, sorry about that, that shouldn't be. I'll fix these tiny plugins to be really self-contained and single-file.

**Comment by joshfuggle** [comment]
All good, thanks mate, using a few of your smaller plugins now. Pulling out uikit atm, so soon will have a minimal amount of js.

**Comment by mosra** [comment]
Fixed in f97aa36211174606bfba36c14fb0e2d16c4ec45c :)
