### ISSUE TITLE
Atom feed _URL variables not populated from FEED_ALL_ATOM

### ISSUE THREAD

**Issue by Squareys** [mosra/m.css#52]
Hey there!

As requested, reporting this issue. If I set my atom feed "save as" variables like this:

~~~
FEED_ALL_ATOM = 'blog/feeds/all.atom.xml'
CATEGORY_FEED_ATOM = 'blog/feeds/%s.atom.xml'
~~~ 

The corresponding _URL links do not get populated from that, i.e.

~~~
  {% if FEED_ALL_ATOM_URL %}
  <link href="{{ FEED_ALL_ATOM_URL|format_siteurl|e }}" type="application/atom+xml" rel="alternate" title="{{ SITENAME|e }}" />
  {% endif %}
~~~

fails the condition and does not add a link to the header.

Cheers and thanks for m.css!
Jonathan.

**Comment by mosra** [comment]
Done in 8e8151293c2a22d50ca2357a284e95670fe07f9c! :)
