### ISSUE TITLE
Missing libgs warning (latex2svg.py) and generation failing... Ubuntu 16.04

### ISSUE THREAD

**Issue by gotchafr** [mosra/m.css#6]
Problem was the name looked for was 'libgs', but on a linux platform it should be 'gs'
On Ubuntu 16.04 find_library gives 'libgs.so.9'
I added two lines after line 57, testing for linux... (I guess I should submit a pull request at @tuxu [latex2svg](https://github.com/tuxu/latex2svg))

```
if not hasattr(os.environ, 'LIBGS') and not find_library('libgs'):
    if sys.platform == 'darwin':
        # Fallback to homebrew Ghostscript on macOS
        homebrew_libgs = '/usr/local/opt/ghostscript/lib/libgs.dylib'
        if os.path.exists(homebrew_libgs):
            default_params['libgs'] = homebrew_libgs
    if sys.platform == 'linux':
            default_params['libgs'] = find_library('gs')
    if not default_params['libgs']:
        print('Warning: libgs not found')

```

And CHANGE latex2svg.py permissions `chmod +x ~/m.css/pelican-plugins/m/latex2svg.py`

Last, but not least, LaTeX packages... (not small ones indeed!)

```
sudo apt-get install texlive-base
sudo apt-get install texlive-latex-extra
sudo apt-get install texlive-fonts-extra
```

**Comment by mosra** [comment]
Fixed in #5 and https://github.com/mosra/m.css/commit/489b91d156e8299820d6be5f3b2d7108d939ca22, I opened a PR upstream already also. Keeping #5 open until I update the docs.
