### ISSUE TITLE
Fix compatibility with matplotlib 3.0

### ISSUE THREAD

**Issue by mosra** [mosra/m.css#64]
The [m.plots](http://mcss.mosra.cz/plugins/plots-and-graphs/#plots) plugin was coded against matplotlib 2.2.3. The 3.0 release is apparently doing a lot of things differently and thus the regexps are not working anymore. Things to do:

- [x] pin the CI to 2.2.3 to keep it green until I have time to look into this
- [x] provide dual compatibility for 2.2.3 and 3.0 (i hope it's possible)
- [x] test with both 2.2.3 and 3.0 on the CI

**Comment by jeljaik** [comment]
Hello mosra! Quick question: Is it possible to do as described in [**Plots and graphs**](http://mcss.mosra.cz/plugins/plots-and-graphs/) in **.dox** files?

**Comment by mosra** [comment]
I'm going to implement support for graphs (the `@dot` / `@dotfile` Doxygen command) in the next week or so, because I need that myself too. Will ping you once it's done :)

**Comment by mosra** [comment]
@jeljaik shipped: 6a289d2a5633f7cb77b9a4330bc5618d75b98a64 I took a few shortcuts, so if something is not working as it should, please open an issue ;)

**Comment by mosra** [comment]
Fixing this was actually simple, apart from new test files for each version basically an one-letter difference. Done in 644658c758fd124a98410954429b8226671532b4 (and b64344b241fa8429cb9b08b0a0f472fd901aed66).
