### ISSUE TITLE
dehyphenate filter appears to not do anything

### ISSUE THREAD

**Issue by Squareys** [mosra/m.css#67]
Hi @mosra !

I have a custom property in a content rst file that contains a bunch of `,` separated urls.
These seem to be hyphenated, so I found `dehyphenate` in the docs. Looking at [the code](https://github.com/mosra/m.css/blob/master/pelican-plugins/m/htmlsanity.py#L696), I can force the function to do something by passing `enable=True` to it. Hence, my final code looks like this:

~~~html
{{script_file|dehyphenate(True)}}
<!-- or -->
{{script_file|dehyphenate(enable=True)}}
~~~

My result is

~~~
[...]/re&shy;leas&shy;es/[...]
~~~

However, if I

~~~
{{script_file|replace("\u00AD", "")}}
~~~

I get the correct result.

Cheers, Jonathan.

**Comment by Squareys** [comment]
Thanks for those solution approaches, will check them this afternoon and report back!

(3. I am certain that it is not, because I tried that and it added `<p>` around the field, so I removed it again, will make sure, though. The others are very plausible, though.)

**Comment by mosra** [comment]
@Squareys did you have a chance to look at this? :)

**Comment by Squareys** [comment]
Alright, so, `M_HTMLSANITY_HYPHENATION=True` is definitely set and for some reason it just works now.
(I did update m.css a couple of times in the meanwhile, though. I may be that I was using a version from July or something 🤔 )

The `&shy;` vs `\u00AD` might have been because of display in the chrome elements view or because I `|e` afterwards.

**Comment by Squareys** [comment]
Hmm, it even works without `dehyphenate`... my have been an issue in my custom content type plugin...

**Comment by mosra** [comment]
Hmm. Okay, closing then :)
