### ISSUE TITLE
Releasing latex2svg as a standalone package

### ISSUE THREAD

**Issue by leouieda** [mosra/m.css#7]
Hi @mosra, great content you have created here!

I'm interested in the `latex2svg.py` code. Having it as a standalone Python package would help others create plugins for different static site generators (I use Urubu).

Would you be willing to do this? If not, would you be OK with someone else doing it (with proper acknowledgement, of course)? I'd be happy to lend a hand.

**Comment by mosra** [comment]
Hi, thanks. Uh, the `latex2svg.py` *is* standalone, I just failed to state that clearly enough :/

It's by @tuxu and the upstream repo is https://github.com/tuxu/latex2svg. In 4d21d5851fddcf086715efae496fb3644015b506 I attempted to give the credit better (sorry).

**Comment by leouieda** [comment]
Oh, that's great! Less work for me as well  :)

Maybe add the credit line to the source file as well? I didn't even look at the CREDITS.txt file, only the source code.

**Comment by mosra** [comment]
I don't want to modify the bundled file, as it makes it harder to pull changes from upstream.

Hopefully now it's clear enough. Closing as resolved :)

**Comment by leouieda** [comment]
I understand. Alright, thanks for the info!
