### ISSUE TITLE
Python documentation support

### ISSUE THREAD

**Issue by mosra** [mosra/m.css#80]
Similar in spirit to #76, I think it could be feasible (and easier to do than for C#) to generate documentation for Python code by introspecting `.__doc__` properties, using [inspect.getmembers()](https://docs.python.org/3/library/inspect.html#inspect.getmembers) and so on. I think that's preferred to trying to parse Python directly (as Doxygen does right now). The goal of this also might be Sphinx compatibility (as in, providing a better search than they have), but unrelated to what's described in #78.

According [to the wiki](https://wiki.python.org/moin/API%20Extraction), it's possible to do this introspection either by importing living code (which can impose some requirements on dependencies) or by parsing a "dead" code (which might not be able to see everything, tho). Needs to be further investigated.

This may get needed once I revive the work on Python bindings in Magnum (https://github.com/mosra/magnum/pull/228).

Things to do:

- [x] basic code introspection and docstring extraction
- [x] external reST docs and pages
- [x] symbol crosslinking
- [x] search
- [x] interfacing with intersphinx

**Comment by mosra** [comment]
Work is happening in the (not-yet-pushed) `python` branch and there's https://github.com/mosra/m.css/projects/8 tracking various implementation issues and stumbling blocks. The initial version will be tailored mainly for the purposes of documenting pybind11 code (i.e., extracting type signatures from it etc.), with support for general Python code and Sphinx-like documentation using reST files appearing later. I'm trying to design this in a way that makes most of the code reusable for the potential new clang-based Doxygen backend replacement.

**Comment by nikhilkalige** [comment]
@mosra  Would be happy to help..

**Comment by mosra** [comment]
@nikhilkalige Thanks! I'll let you know once I have some minimal design done (next week or two), right now everything is quite in flux and we would be only stepping on each other's toes :) Since your code is also a mixture of pybind11 and C++, I assume your use case would be pretty similar to mine (so requiring a similar set of features), right? 

The "minimum viable product" for me is in the "Important TODO" and "In Progress" columns in the above-linked project, once I have those done I'll push the code and open up the development.

**Comment by nikhilkalige** [comment]
It seems you will be using pybind, mine is more along the lines of
```sh
lib1/
  doc/
    index.rst
  src/ 
    #   cpp files
  public_include 
    # header files
  python/
    setup.py
    lib1/ 
      # python files
lib2/
  ....
lib3
  ....
```
My idea was along the lines of index.rst would have some doc page for the library and I would link the C++ API docs and the Python Api docs into that rst file.

Let me know how when you are done, I will try to adapt from your design.

**Comment by mosra** [comment]
Finally managed to continue working on this. Sometimes I feel like I should clone myself to be able to work on all the fun things at once :)

Right now what I'm doing is inspecting contents of a Python module, generating a "Doxygen-style" list of functions, enums, classes, data, ... with all annotations and signatures that can be extracted this way. Taking the docstrings as "brief docs". This is the MVP I need right now -- so people are able to search for APIs, see their signatures and minimal description.

After that, since the above doesn't generate *any* index page (or, well, any page at all), I need to hook up docutils for the reST processing and then add a (Sphinx-inspired) way to reference the APIs from the prose.

Do I understand correctly that you want to have *both* C++ and Python APIs in a single documentation? Right now, and mainly because Doxygen is *extra special* when it comes to generating filenames and references, I'm not sure if this will be possible, however once I add support for `intersphinx` and/or Doxygen tag files to the Python part, it should be possible to crosslink C++ from Python docs and Python from C++ docs. Then, if you organize the top navbar, URLs and page names in a certain way I think it could be possible to "overlay" the two (basically having the same output path for both) and make them appear like a single site.

I'll think further about the possibility to have both C++ and Python combined in a single thing -- my initial idea (for [Magnum](https://magnum.graphics)) was to have a separate site for C++ and Python APIs, but the more I think about it the more it seems it could make sense to have them combined. One thing I'm not sure about is the search -- when searching, the user will probably want to always search only for either C++ or Python APIs, *not* have both appear in the results.

**Comment by nikhilkalige** [comment]
How are you extracting the docstrings? Is your idea to import the file and extract it using `inspect`? 

I have come to hate importing the file to extract the docs, this means that you have to build the tree, as the packages are usually dependent on other packages that are also in the tree, as well as packages that come from the internet and mocking each of them doesn't seem to work very well.

The other way of extracting the docstring would be using `ast` module.

Please let me know your thoughts..

**Comment by mosra** [comment]
Yes, it's `inspect`, that's the only way which works for both python source files and native modules (pybind11, python C internals or whatever other bindings). Yes, it means the source needs to be runnable on given machine, but AFAIK both Sphinx and pydoc need that too (Doxygen doesn't because it parses the files directly, but it has tons of other problems caused by exactly that). Next step is adding a possibility to use reST files instead of (or in addition to) in-source docstrings.

I just pushed the first version in #98, it has some rough docs and there's still essential stuff to do regarding search, but I think at the design is already starting to get settled down quite well.

**Comment by mosra** [comment]
Initial version got just merged, the next steps are integrating reST sources, crosslinking and search.

**Comment by nikhilkalige** [comment]
Awesome.. Will try it out today..

**Comment by mosra** [comment]
Latest update:

- support for arbitrary reST pages in a4ec3e96718c9522aaaa68e102a3fd962d1c7c1b
- support for externally supplied module, class and data docs in aa5db04b0ea07bcafc04c96b2af0941eb6f58785
- support for external plugins (and reusing everything m.css already has, like code highlighting, graphs, plots, images, ...) in 7da9f16733fa05658e5d9ae423dbb7f3d5e513ec

Next step is name crosslinking and search.

**Comment by mosra** [comment]
Finished:

- search done since 8ecfe5c0b0223c1fa8c4c3deafeb86522aa02e3f
- intersphinx read support in 4937298ceb278769bae07601328618a28c0210a7
- symbol crosslinking in 87ed31ef6afbb971095a30fe0ae6d8ff918b5a40 and 810fd115851c641aa038a1968659c98dbd8a48f7
- and intersphinx write support in 597ebe99163192fb6daf2e6a45f87eb0095a3d23

Documentation for everything is at https://mcss.mosra.cz/documentation/python/ and https://mcss.mosra.cz/plugins/sphinx/. What's left is non-critical things like adding various options to class/function/... directives and support for reST parsing in docstrings and not just external files. Those will get added on an as-needed basis, but the major part of the work is done here.

@crisluengo I saw you have Python bindings in DIPlib, wanna be an early adopter for this? :grin:

**Comment by crisluengo** [comment]
@mosra I’d love to! ...except I still don’t have any freaking docstrings in my Python bindings. I use Pybind11, and need some way to copy the C++ Doxygen docs to Python docstrings. :)

**Comment by mosra** [comment]
I use pybind11 too :) So far everything I exposed via pybind is just one-line docstrings and the docs are just "delta" to the c++ documentation (e.g. https://doc.magnum.graphics/python/magnum.math.html) -- showing differences, best practices, but referring to the c++ docs for full description of each API. I'm planning to add some automatic way to have each python API crosslinked with its c++ equivalent, which would help, but other than that I didn't even think about bringing the full c++ docs over to the python side. Too much work :)
