### ISSUE TITLE
Doxygen: SHOW_NAMESPACES=NO doesn't seem to be honored

### ISSUE THREAD

**Issue by kobalicek** [mosra/m.css#87]
Or is there some other way of disabling the namespaces page?

**Comment by kobalicek** [comment]
Not sure this is a valid issue since this can be configured via NavBar settings.

**Comment by mosra** [comment]
Hi!

Frankly I was not aware that this option exists (there's way too many Doxyfile options in my opinion), so I did not implement it :)

OTOH, as you discovered, the navbar settings are a much more flexible way to configure this behavior, however they don't affect whether the various `pages.html`, `namespaces.html` etc. files are generated. So even if you hide it from the navbar, the files are still present.

Um.... wait, if this is set to `NO` and you still have namespaces, do the namespace links still work in the stock HTML output? Or where do they point? I'm not sure how this option should behave in that case.

**Comment by kobalicek** [comment]
I used this with doxygen to hide the "namespaces" section in the menu itself, haven't actually checked whether it has any other effects. Since I figured out how to use navbar settings this could be probably closed.

**Comment by mosra** [comment]
Keeping this open, the very least I can do about this is mentioning this limitation in the docs.

**Comment by mosra** [comment]
Documented in 0f33d3151b3795e48314be022c084784a2ec5293 (and [here](https://mcss.mosra.cz/doxygen/#intentionally-unsupported-features)).
