### ISSUE TITLE
Internal documentation showing even when INTERNAL_DOCS=NO

### ISSUE THREAD

**Issue by kobalicek** [mosra/m.css#88]
I'm having some problems with internal namespaces, classes, and functions. I wrote a small example:

```c++
//! \internal
//! \{

//! \defgroup internal_group Internal
//! \brief Internal API

//! \}

//! \ingroup internal_group
//! \brief Something A
class A {};

//! \internal
//! \{

//! \addtogroup internal_group
//! \{

//! \brief Something B
class B {};

//! \}
//! \}

//! \addtogroup internal_group
//! \{

//! \internal
//! \{

//! \brief Something C
class C {};

//! \}
//! \}

//! \internal
//! \{

//! \brief Something D
//! \ingroup internal_group
class D {};

//! \}

//! \internal
//! \{

//! \brief Something E
class E {};

//! \}

//! \internal
//! \brief Something F
class F {};
```

I set `INTERNAL_DOCS=NO`, but I still see these in my documentation. I'm not sure this isn't a doxygen problem instead, but since `m.css` hides automatically undocumented members I was wondering whether it would be possible to hide also internals when INTERNAL_DOCS=NO.

**Comment by mosra** [comment]
The theme doesn't have support for this yet (I didn't need this myself, the theme was done on an as-needed basis, and you're the first asking for this kind of functionality). I'm not sure how this is exposed to the XML output -- I hope it is, but my experience shows that a lot of features actually isn't propagated there. If Doxygen exposes this properly to the XML output, the implementation could be rather straightforward.

I am pretty busy at the moment, so I'm afraid I can't look at this sooner than end of next week (and besides that I already have quite a significant backlog of other feature requests here). Is that okay? :)

**Comment by kobalicek** [comment]
Yeah of course, I didn't expect it to be done overnight :)

I have a big large project that has a smaller public API and a lot of documented internals, however, I'm really struggling about documenting them properly, because these internals are then mixed with the documentation. 

I have done some digging and I found this. If I set INTERNAL_DOCS=NO then it's all bad as there is no way of identifying internals from the XML output. However, if I set `INTERNAL_DOCS=YES` then each internal symbol would have `<internal></internal>` element in its data, which I guess can be used to filter these symbols out.

For example, the output XML would look like this:

```xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.15">
  <compounddef id="class_c" kind="class" language="C++" prot="public">
    <compoundname>C</compoundname>
    <includes local="no">test.h</includes>
    <briefdescription>
<para>Something <ref refid="class_c" kindref="compound">C</ref>. </para>
    </briefdescription>
    <detaileddescription>
<internal></internal>
    </detaileddescription>
    <location file="test.h" line="32" column="1" bodyfile="test.h" bodystart="32" bodyend="32"/>
    <listofallmembers>
    </listofallmembers>
  </compounddef>
</doxygen>
```

Which would be enough to filter these out I think. Let me know when you get some time, I can describe how it could work, but I don't know whether I'm able to do it myself.

**Comment by mosra** [comment]
> I have a large project

Is it asmjit? *That* would be an honor :)

> However, if I set `INTERNAL_DOCS=YES` then each internal symbol would have `<internal></internal>` element in its data, which I guess can be used to filter these symbols out.

Yes, definitely. Good to know. Should be quite easy to do, yes. Will ping you back once I have something.

**Comment by kobalicek** [comment]
Yeah :) I would like to have some minimum documentation online for both AsmJit and Blend2D projects. I don't really like the default doxygen output, but yours look much saner and if everything works out it would save me some time to write my own generator :)

**Comment by kobalicek** [comment]
I think this issue should be marked as Invalid. Doxygen states that `\internal` is only to omit text in the documentation, but not to omit symbols. Doxygen recommends using `\cond` and `\endcond` for globally ignoring parts of source code, which I started using and seems to work.

This all means that I just misunderstood the meaning of `\internal` and created a wrong issue. Don't waste time on this :)

**Comment by mosra** [comment]
> Doxygen recommends using `\cond` and `\endcond` for globally ignoring parts of source code

I'm personally either putting all the "internals" into some `Implementation` namespace (and then ignoring that namespace in Doxyfile) or using a preprocessor macro for hiding stuff from Doxygen completely (e.g. `#ifndef DOXYGEN_GENERATING_OUTPUT`, with this macro added to the `PREDEFINED` setting in Doxyfile.

I still think support for `\internal` could be valuable to somebody someday, keeping this open so people who may need it can speak up. Implementing support for this boils down to recognizing the `<internal>` tag in `parse_desc_internal()` and either including or excluding the contents based on the value of `INTERNAL_DOCS`. If I'm not mistaken, stuff wrapped inside `\internal` and `\endinternal` would be currently unconditionally ignored (most probably with a warning about unknown `<internal>` tag being printed) , right?

**Comment by kobalicek** [comment]
Yeah, doxygen interprets `\internal` as a means to only document internals and considers it like any other html tag type. So when you use `\internal` it keeps it if `INTERNAL_DOCS=YES`, but omits it otherwise. The `\cond` command on the other hand works like a C preprocessor and is global, so it's much saner to use it to document internals.

For example in an internal header file you can put `\cond INTERNAL` at the beginning and `\endcond` at the end and the content of the file would only appear in the documentation if you enable INTERNAL in `ENABLED_SECTIONS`.

**Comment by kobalicek** [comment]
I'm closing this issue as I think it's invalid. For anyone facing a similar problem: use `\cond` and `\endcond`.

**Comment by kobalicek** [comment]
BTW I don't think you should implement anything from here, it was my misinterpretation of `\internal` keyword and doxygen does exactly what it should do here.

**Comment by mosra** [comment]
Well, this was actually *fun* to implement, unlike all the other crazy doxygen bugs i had to plow through today. Done in 9c5b329e3a4acce7aaca540923989313d5730c2c.
