### ISSUE TITLE
Doxygen: Output undocumented symbols, possibly implement `HIDE_UNDOC_...`

### ISSUE THREAD

**Issue by kobalicek** [mosra/m.css#90]
I know that it's stated in the documentation:

  "Files, di­rec­to­ries and sym­bols that don’t have any doc­u­men­ta­tion are not present in the out­put at all."

However, I think it's unfortunate. I would be fine with files/directories as these don't mean much to people reading documentation, but removing undocumented symbols means that projects that don't have 100% documentation coverage would never be able to use m.css as the output would be incomplete. In many cases just seeing the name of the symbol is self-explanatory and especially getters/setters usually don't need redundant "sets XXX property" documentation unless the getter/setter does something extra.

So I'm asking whether it would be possible to relax this constraint or maybe better to handle these doxygen options:

  * `HIDE_UNDOC_MEMBERS`
  * `HIDE_UNDOC_CLASSES`
  * maybe others, but these seem the most important

I know your statement about this, but I tried anyway :)

**Comment by kobalicek** [comment]
A possible duplicate of #72 - I used "Undocumented" keyword to search issues without results.

**Comment by mosra** [comment]
Yes, so closing as duplicate :) I'll finally have some time to work on this project today afternoon and during the weekend, the reports are getting slightly out of hand :sweat_smile:
