### ISSUE TITLE
Function already in trailing return format

### ISSUE THREAD

**Issue by zhi-zhang** [mosra/m.css#94]
Given a function that is already in trailing return format: `auto` foo() -> void;`

The theme will format it to `auto foo() -> void -> auto`

It should ignore auto return type as well as void.

**Comment by mosra** [comment]
Hi!

Sorry to disappoint but this is, as far as I'm aware from when I was doing extensive testing of this functionality in 193ab8059f56d0ae3dd470fe3dc180d460878151, a problem in Doxygen itself, where already the XML output m.css is consuming has the types messed up and there's not a lot I can do to fix that :(

Two possible solutions:

- report this bug to Doxygen and get them to fix this (ideally including a minimal example and a corresponding snippet of the XML output that shows the bad parsing), if you do please reference the bugreport here so I can track it as well -- thank you! Be prepared that this might take them quite a while to get fixed tho (months or even years, sometimes).
- or work around this in your codebase by not having a trailing return type for Doxygen, for example:
  ```cpp
  #ifndef DOXYGEN_GENERATING_OUTPUT
  auto foo(T a) -> typename complex_return_type<decltype(a+2)>::something
  #else
  typename complex_return_type<decltype(a+2)>::something foo(T a) 
  #endif
  {
      ...
  ```
  (and then `DOXYGEN_GENERATING_OUTPUT` being in the `PREDEFINED`  option in your Doxyfile). This is a workaround I'm doing quite often -- Doxygen doesn't care as much about correctness of the code and parses it acceptably well, it's ugly but better than having the docs look broken.

Have a nice day!

**Comment by zhihao50** [comment]
I have worked around it by modifying the entry-func.html to not display return type for function with auto return type similar to how void is handled.
