### ISSUE TITLE
Doxygen: HTML entities ignored

### ISSUE THREAD

**Issue by crisluengo** [mosra/m.css#99]
I use a few HTML tags and entities and  in my documentation. These are ignored by `doxygen.py`. For example, I use `2<sup>nd</sup>` and `&rarr;`. This is what I get:

```
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <rarr> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <superscript> in desc
WARNING:root:changes.xml: ignoring <lsquo> in desc
WARNING:root:changes.xml: ignoring <rsquo> in desc
WARNING:root:changes.xml: ignoring <lsquo> in desc
WARNING:root:changes.xml: ignoring <rsquo> in desc
WARNING:root:changes.xml: ignoring <lsquo> in desc
WARNING:root:changes.xml: ignoring <rsquo> in desc
```

**Comment by mosra** [comment]
Hello, thanks for the report!

Yes, these were added on an as-needed basis and there is quite a few of them missing (I would say majority of them is not handled, even). Unfortunately at the moment I have no time to look into this and add the remaining ones, earliest I could have a look is end of next week. 

If you do not want to wait or you are willing to dig in the code yourself, you're welcome to submit a PR with the mising ones -- the place where those would need to get added is [here](https://github.com/mosra/m.css/blob/9be0ed4634d1c95358644e9f376fa2f8598d4110/documentation/doxygen.py#L1520) and then extending the test input [here](https://github.com/mosra/m.css/blob/9be0ed4634d1c95358644e9f376fa2f8598d4110/documentation/test_doxygen/contents_typography/input.dox#L37) -- if you [run the tests](https://github.com/mosra/m.css/blob/master/CONTRIBUTING.rst#running-tests) (or submit a PR), it will tell you how the corresponding expected output in `index.html` needs to be updated. Thanks in advance! :)

**Comment by crisluengo** [comment]
Thanks for the pointers, I will look into this.

**Comment by crisluengo** [comment]
When I do
```
cd documentation
python -m unittest
```
I see:
```
Ran 0 tests in 0.000s

OK
```

Am I missing something?

**Comment by mosra** [comment]
Is python python2 or python3? It should be python3, otherwise it won't work.

**Comment by crisluengo** [comment]
Yes, indeed. I keep forgetting that `python` is Python 2, not 3. Thank you.

**Comment by mosra** [comment]
#100 is merged now, thank you! Also congrats for having a :100: th PR :tada: :sunglasses:
